FROM cirrusci/windowsservercore:2019

RUN powershell -Command \
    choco install -y --no-progress nodejs --version 10.15.1 ; \
    choco install -y --no-progress yarn ; \
    choco install -y --no-progress --ignore-dependencies msys2 vcredist2015 ; \
    refreshenv
