FROM cirrusci/windowsservercore:2019

RUN powershell -Command \
    choco install -y --no-progress nodejs yarn ; \
    choco install -y --no-progress --ignore-dependencies msys2 vcredist2015 ; \
    refreshenv
