FROM cirrusci/windowsservercore:2019

RUN powershell -Command \
    choco install -y --no-progress nodejs --version 10.15.1 ; \
    choco install -y --no-progress yarn ; \
    choco install -y --no-progress msys2 ; \
    choco install -y --no-progress vcredist2015 ; \
    refreshenv
